### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by icf20** [avpnusr/torprivoxy#12]
`[warn] Failed to parse/validate config: Couldn't create private data directory "//.tor"`

`[warn] Error creating directory //.tor: Permission denied`

**Comment by avpnusr** [comment]
Thank you for bringing this to my attention!
What architecture are you running the container on? ARM, x64 or anything else?

I can't reproduce the warnings by now, do they occure on the start of the container?

Regards, avpnusr
