### ISSUE TITLE
obfs4proxy and bridges

### ISSUE THREAD

**Issue by crnah2o** [avpnusr/torprivoxy#23]
Hi!

First of all, many thanks for this docker. Using it on Unraid; tried both the alpine and debian versions of docker but can't figure out how to:

a) edit torrc to add bridges and point to the obfs4proxy binary on debian version of container

or

b) add obfs4proxy to the alpine version and point to it in torrc

Could you please help? I'm a total noob when it comes to dockers, so maybe it's a stupid question - is it possible for you to expose options for using obfs4proxy and bridges to the unraid docker setup config?

Thanks in advance

**Comment by skrashevich** [comment]
Implemented on PR #30

**Comment by r35p3ct** [comment]
Am I adding variables correctly?
![image](https://github.com/avpnusr/torprivoxy/assets/7328803/3876a941-6235-45c7-a9d7-a2b3d6db6f3e)
