### ISSUE TITLE
Questions about this Proxy

### ISSUE THREAD

**Issue by dandud100** [avpnusr/torprivoxy#49]
So if i am understand this right, it will give us the ability to proxy using the tor network with privoxy over http, right?

First question: Why not https?

Second question: Will it use a new identity / new ip for every api request to the same linux-iso indexer requested from radarr for example?

Third question: Does it include an kill-switch?

Fourth question: Will it prevent things such as DNS-Leaks and does it block ipv6? (Not sure if ipv6 is usable over tor.)

Fifth question: How can i verify if this proxy is working successfully? Like is there any test i can do from any other docker containers shell?

Thank you! :)

**Comment by avpnusr** [comment]
Hey @dandud100 sorry for the late answer, but I was quite busy the last few weeks / months.

I try to answer your questions as good as I can :)

1. The Connection  to the proxy itself is afaik never https, as the client uses the CONNECT method to access a webpage through the proxy, which itself opens (if the site offers https) a SSL/TLS encrypted TCP connection. The proxy just receives and transmits the packets and doesn't even care, that it knows nothing about the contents of the packets - so in my opinion the connection is as secure, as directly connecting to a https website

2. At the moment, it will not create a new identity for every api-request, as I set on the standard behaviour of switching identities every 10 minutes (estimated time). The less special the TOR-daemon runs, the more unidentifiable in my eyes ;) Perhaps you find a way, and will share it as an optional setting with me.

3. Nope, no kill-switch at the moment, but the container will put itself into an unhealthy state, if no connection to the tor-network is established and the proxy-itself won't work, if the tor-service is not connected, as the SOCKS-Connection to the TOR-service is dead. 

4. It will not prevent those things by itself. You have to configure your client and browser properly to prevent such leakage

5. You can verify, if the proxy is working by using it. If you can successfully retrieve a webpage, the proxy works. If you want to test TOR itself, just try to open an *.onion webpage, as the container does for it's healthcheck. It tries to get the *.onion page for duckduckgo.com "https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion". If that works, the TOR-service works perfectly. You can test this even from another container with i.e. "curl" using the proxy-server to retrieve the page. For an example, see how I do it in the healthcheck in the [Dockerfile](https://github.com/avpnusr/torprivoxy/blob/6c068d89f9e86cf829771860334d0ee691f515a9/Dockerfile#L41C1-L41C189) 

I hope this helps you somehow

**Comment by crnah2o** [comment]
I was just passing by, have seen you question and thought of sharing my experience(s). Please have in mind that I'm a total noob, I don't know anything about any of this and am just sharing my experiences hoping I'll help you in further research. Any of the stuff I suggest/say might be untrue (probably most is only partialy true) and can break stuff.

> So if i am understand this right, it will give us the ability to proxy using the tor network with privoxy over http, right?
and through socks

> First question: Why not https?
you can do https through socks

> Second question: Will it use a new identity / new ip for every api request to the same linux-iso indexer requested from radarr for example?
I have no idea. about this I, however, do have a comment - IIRC, tor people ask kindly not to use torrent through tor network, so it'd be nice if you could recpect that. There are other ways....

> Third question: Does it include an kill-switch?
I don't think so.

> Fourth question: Will it prevent things such as DNS-Leaks and does it block ipv6? (Not sure if ipv6 is usable over tor.)
I'm not sure how you're implementing this or what for; maybe think of building a (virtual?) system/container that has the only connection to the internet through tor socks proxy, setting that up both on that system and in your network and you probably should be OK. Don't know anything about IPv6.

> Fifth question: How can i verify if this proxy is working successfully? Like is there any test i can do from any other docker containers shell?
Well, as I've said above, I do it in such a way that I verify that the system/app cannot reach anything when tor (proxy) is down. Also, tor has a "check" command you can run in this docker if you'd like to know if tor is connected, but I can't remember it exactly
